name: Flutter CI

on:
  push:
    branches:
      - main    # Trigger on push to the main branch
  pull_request:
    branches:
      - main    # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]  # Test on all major platforms
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'   # Specify the Flutter version, e.g., '2.10.4'
        
      - name: Install dependencies
        run: flutter pub get
        
      - name: Run Flutter analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test
with:
  flutter-version: 'stable'
